### ISSUE TITLE
Improve test reporting

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#1273]
We have less noise in the test reporting now thanks to #1258. But it's still really subpar.

Consider this example of output from a failing test, shared by @gabrielamafra:

```
[I] gabriela@gabriela-nixos ~/p/apalache (gabriela/passes-dependency)> sbt test
[info] welcome to sbt 1.6.1 (N/A Java 16)
[info] loading settings for project apalache-build-build-build from metals.sbt ...
[info] loading project definition from /home/gabriela/projects/apalache/project/project/project
[info] loading settings for project apalache-build-build from metals.sbt ...
[info] loading project definition from /home/gabriela/projects/apalache/project/project
[success] Generated .bloop/apalache-build-build.json
[success] Total time: 0 s, completed Jan 31, 2022, 1:29:41 PM
[info] loading settings for project apalache-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /home/gabriela/projects/apalache/project
[success] Generated .bloop/apalache-build.json
[success] Total time: 1 s, completed Jan 31, 2022, 1:29:42 PM
[info] loading settings for project root from build.sbt ...
[info] set current project to apalache (in build file:/home/gabriela/projects/apalache/)
[info] - 2 passes, OK *** FAILED *** (81 milliseconds)
[info]   java.lang.ClassCastException: class jdk.proxy3.$Proxy9 cannot be cast to class at.forsyte.apalache.infra.passes.TlaModuleMixin (jdk.proxy3.$Proxy9 is in module jdk.proxy3 of loader sbt.internal.LayeredClassLoader @70fd5f07; at.forsyte.apalache.infra.passes.TlaModuleMixin is in unnamed module of loader sbt.internal.LayeredClassLoader @70fd5f07)
[info]   at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:30)
[info]   at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:47)
[info]   at at.forsyte.apalache.infra.passes.TestPassChainExecutor.$anonfun$new$2(TestPassChainExecutor.scala:25)
[info]   at org.scalatest.easymock.EasyMockSugar.whenExecuting(EasyMockSugar.scala:422)
[info]   at org.scalatest.easymock.EasyMockSugar.whenExecuting$(EasyMockSugar.scala:415)
[info]   at at.forsyte.apalache.infra.passes.TestPassChainExecutor.whenExecuting(TestPassChainExecutor.scala:9)
[info]   at at.forsyte.apalache.infra.passes.TestPassChainExecutor.$anonfun$new$1(TestPassChainExecutor.scala:22)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   ...
[info] Run completed in 233 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[info] TestPassChainExecutor:
[info]
[info] - 2 passes, OK *** FAILED *** (81 milliseconds)
[info]   java.lang.ClassCastException: class jdk.proxy3.$Proxy9 cannot be cast to class at.forsyte.apalache.infra.passes.TlaModuleMixin (jdk.proxy3.$Proxy9 is in module jdk.proxy3 of loader sbt.internal.LayeredClassLoader @70fd5f07; at.forsyte.apalache.infra.passes.TlaModuleMixin is in unnamed module of loader sbt.internal.LayeredClassLoader @70fd5f07)
[info]   at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:30)
[info]   at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:47)
[info]   at at.forsyte.apalache.infra.passes.TestPassChainExecutor.$anonfun$new$2(TestPassChainExecutor.scala:25)
[info]   at org.scalatest.easymock.EasyMockSugar.whenExecuting(EasyMockSugar.scala:422)
[info]   at org.scalatest.easymock.EasyMockSugar.whenExecuting$(EasyMockSugar.scala:415)
[info]   at at.forsyte.apalache.infra.passes.TestPassChainExecutor.whenExecuting(TestPassChainExecutor.scala:9)
[info]   at at.forsyte.apalache.infra.passes.TestPassChainExecutor.$anonfun$new$1(TestPassChainExecutor.scala:22)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   ...
[error] Failed tests:
[error] 	at.forsyte.apalache.infra.passes.TestPassChainExecutor
[info] compiling 1 Scala source to /home/gabriela/projects/apalache/tla-assignments/target/scala-2.12/classes ...
[info] compiling 1 Scala source to /home/gabriela/projects/apalache/tla-bmcmt/target/scala-2.12/classes ...
[info] Run completed in 213 milliseconds.
[info] Total number of tests run: 14
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 14, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Run completed in 7 seconds, 261 milliseconds.
[info] Total number of tests run: 455
[info] Suites: completed 12, aborted 0
[info] Tests: succeeded 455, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] - the tool consumes its output on TlcSpec1 !!! IGNORED !!!
[info] Run completed in 25 seconds, 77 milliseconds.
[info] Total number of tests run: 222
[info] Suites: completed 14, aborted 0
[info] Tests: succeeded 222, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Run completed in 25 seconds, 28 milliseconds.
[info] Run completed in 25 seconds, 9 milliseconds.
[info] Total number of tests run: 183
[info] Suites: completed 11, aborted 0
[info] Total number of tests run: 164
[info] Tests: succeeded 183, failed 0, canceled 0, ignored 1, pending 0
[info] Suites: completed 17, aborted 0
[info] Tests: succeeded 164, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] All tests passed.
[info] Run completed in 31 seconds, 700 milliseconds.
[info] Total number of tests run: 160
[info] Suites: completed 22, aborted 0
[info] Tests: succeeded 160, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] (infra / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 33 s, completed Jan 31, 2022, 1:30:16 PM
```

It reports the failing test on the last line, but right above it (in bright green, btw), is the deceptive claim "All tests passed". And to find the actual test failure output, we have to scroll back to the location of the failing test.

The underlying cause seems to be that the output being generated by Scalatast doesn't really have multi-project structures in mind. The tests results for each project are being reported as if it they were only set of sets.

There *must* be a way to get nicer test reporting. This is not just an aesthetic concern, since it has a direct impact on the length of iteration cycles between devs hitting failing tests and them figuring out the reason for the failure.

**Comment by konnov** [comment]
nice but no one would implement it
